name: Build Spring Boot Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out your repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Java 23 using the setup-java action
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '23'

      # Build your Spring Boot project with Maven
      - name: Build with Maven
        run: mvn clean package
